### ISSUE TITLE
Use block-chomping indicator in yaml output

### ISSUE THREAD

**Issue by ArchLeaders** [Nintendo-EPD/msbt#3]
Fixes incorrect line endings when using a dedicated yaml parser.

Reported from https://github.com/NX-Editor/NxEditor.CeadPlugin/issues/1

**Comment by jordanbtucker** [comment]
When convering an MSBT file to YAML, the generated YAML uses [Literal Style](https://yaml.org/spec/1.2.2/#812-literal-style) blocks without the [Block Chomping Indicator](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator), so the text always includes an ending line break. When converting the YAML to something else, like JSON, this preserves the ending line breaks that don't actually exist in the MSBT.

For example, `ActorMsg/PouchContent.msbt` inside `Mals/USen.Product.110.sarc.zs` contains item names and descriptions when viewing them from the inventory. Here's a snippet of YAML produced by NxEditor.

```yaml
Armor_035_Head_Caption: |
  According to legend, this cap was crafted for
  a hero who travels the wild lands. A Great
  Fairy has increased its defense by one level.
Armor_042_Head_Name: |
  Stealth Mask
```

When converting this YAML to JSON, you get the following.

```json
{
  "Armor_035_Head_Caption": "According to legend, this cap was crafted for\na hero who travels the wild lands. A Great\nFairy has increased its defense by one level.\n",
  "Armor_042_Head_Name": "Stealth Mask\n"
}
```

Notice that both entries contain ending line breaks (`\n`) which aren't present in the original MSBT file.

This fix for this is to use YAML's [Block Chomping Indicator](https://yaml.org/spec/1.2.2/#8112-block-chomping-indicator) like this.

```yaml
Armor_035_Head_Caption: |-
  According to legend, this cap was crafted for
  a hero who travels the wild lands. A Great
  Fairy has increased its defense by one level.
Armor_042_Head_Name: |-
  Stealth Mask
```

Note the `|-` literal indicators instead of `|`. When converting this to JSON, you get the correct result.

```json
{
  "Armor_035_Head_Caption": "According to legend, this cap was crafted for\na hero who travels the wild lands. A Great\nFairy has increased its defense by one level.",
  "Armor_042_Head_Name": "Stealth Mask"
}
```

Note that the line breaks inside the text are preserved as they exist in the original MSBT, but the ending line breaks are removed as they should be.
